<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Peer Review Assignment - Data Engineer - Extract API Data

Estimated time needed: **20** minutes

## Objectives

In this part you will:

-   Collect exchange rate data using an API
-   Store the data as a CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [ ]:
#!pip install pandas
#!pip install requests

## Imports

Import any additional libraries you may need here.

In [2]:
import requests
import pandas as pd

## Extract Data Using an API

Using ExchangeRate-API we will extract currency exchange rate data. You can see a preview of the data here [https://api.exchangeratesapi.io/latest?base=USD](https://api.exchangeratesapi.io/latest?base=USD&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork-23455645&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork-23455645&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).

### Call the API

 <b> Question 1</b> Using the `requests` library call the endpoint given above and save the text, remember the first few characters of the output:

In [10]:
import urllib.request as request
import json
with request.urlopen('https://api.exchangeratesapi.io/latest?base=USD') as response:
    if response.getcode() == 200:
        source = response.read()
        data = json.loads(source)
    else:
        print('An error occurred while attempting to retrieve data from the API.') 
print(data['rates'])

{'CAD': 1.2609770162, 'HKD': 7.753604086, 'ISK': 128.1818930719, 'PHP': 48.4768102809, 'DKK': 6.1263695527, 'HUF': 295.3291045391, 'CZK': 21.294175797, 'GBP': 0.7126451932, 'RON': 4.0166405799, 'SEK': 8.2650959717, 'IDR': 14082.5521047862, 'INR': 72.5055605898, 'BRL': 5.4067880386, 'RUB': 73.8190130983, 'HRK': 6.2426888541, 'JPY': 105.2887387758, 'THB': 29.9744624763, 'CHF': 0.893895708, 'EUR': 0.8237910866, 'MYR': 4.0405305215, 'BGN': 1.6111706071, 'TRY': 6.9585633083, 'CNY': 6.4517670319, 'NOK': 8.4104950984, 'NZD': 1.3709531263, 'ZAR': 14.613312464, 'USD': 1.0, 'MXN': 20.3553834748, 'SGD': 1.3229261059, 'AUD': 1.2723453332, 'ILS': 3.2704506137, 'KRW': 1103.5423016723, 'PLN': 3.6930554411}

### Save as DataFrame

 <b> Question 2</b>  Using the data gathered turn it into a `pandas` dataframe. The dataframe should have the Currency as the index and `Rate` as their columns. Make sure to drop unnecessary columns.

In [32]:
# Turn the data into a dataframe
df =  pd.DataFrame(data['rates'].items(), columns = ["Currency","Rates"])
df

   Currency         Rates
0       CAD      1.260977
1       HKD      7.753604
2       ISK    128.181893
3       PHP     48.476810
4       DKK      6.126370
5       HUF    295.329105
6       CZK     21.294176
7       GBP      0.712645
8       RON      4.016641
9       SEK      8.265096
10      IDR  14082.552105
11      INR     72.505561
12      BRL      5.406788
13      RUB     73.819013
14      HRK      6.242689
15      JPY    105.288739
16      THB     29.974462
17      CHF      0.893896
18      EUR      0.823791
19      MYR      4.040531
20      BGN      1.611171
21      TRY      6.958563
22      CNY      6.451767
23      NOK      8.410495
24      NZD      1.370953
25      ZAR     14.613312
26      USD      1.000000
27      MXN     20.355383
28      SGD      1.322926
29      AUD      1.272345
30      ILS      3.270451
31      KRW   1103.542302
32      PLN      3.693055

In [34]:
# Drop unnescessary columns
df.set_index("Currency",inplace=True)
df

                 Rates
Currency
CAD           1.260977
HKD           7.753604
ISK         128.181893
PHP          48.476810
DKK           6.126370
HUF         295.329105
CZK          21.294176
GBP           0.712645
RON           4.016641
SEK           8.265096
IDR       14082.552105
INR          72.505561
BRL           5.406788
RUB          73.819013
HRK           6.242689
JPY         105.288739
THB          29.974462
CHF           0.893896
EUR           0.823791
MYR           4.040531
BGN           1.611171
TRY           6.958563
CNY           6.451767
NOK           8.410495
NZD           1.370953
ZAR          14.613312
USD           1.000000
MXN          20.355383
SGD           1.322926
AUD           1.272345
ILS           3.270451
KRW        1103.542302
PLN           3.693055

### Load the Data

Using the dataframe save it as a CSV names `exchange_rates_1.csv`.

In [30]:
# Save the Dataframe
df.to_csv('exchange_rates_1.csv')

Your CSV should be in this format with more currencies

|     | Rates         |
| --- | ------------- |
| CAD | 1.2770677002  |
| HKD | 7.7512162942  |
| INR | 73.7779335367 |
| EUR | 0.8246062505  |

## Authors

Ramesh Sannareddy, Joseph Santarcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork-23455645&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork-23455645&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).